export const codeJourneyAnimation = `const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];
const pop=x=>{x=clamp(x);return 1+2.70158*Math.pow(x-1,3)+1.70158*Math.pow(x-1,2)},smooth=x=>{x=clamp(x);return x*x*(3-2*x)},mix=(a,z,q)=>a+(z-a)*q;
const set=(el,a)=>{el.style.opacity=String(clamp(a));el.style.visibility=a>0?'inherit':'hidden'};
const panes=$$('.code-lines');for(const pane of panes){for(let i=0;i<31;i++){const line=document.createElement('div');line.className='code-line';const no=document.createElement('span');no.className='line-no';const text=document.createElement('span');text.className='line-text';line.append(no,text);pane.append(line)}}
const paintCode=(pane,characters,offset=0)=>{[...pane.children].forEach((row,i)=>{const n=i+offset,text=data.codeSamples[n%data.codeSamples.length];row.children[0].textContent=String(n+1);row.children[1].textContent=text.slice(0,Math.max(0,Math.floor(characters-i*62)));})};
const origins=[260,290,300],targets=[400,540,680],stamp=['1.36s','2.84s','0.72s'];
return frame=>{const f=frame,b=data.beats,water=fade(f,b.water,b.resume,6),solution=ease((f-b.solution)/18),resumed=ease((f-b.resume)/12);
 set($('.code-ground'),f<b.water?1:resumed);set($('.routes'),f<b.water?1:resumed);$('.routes').style.transform='translateY('+mix(400,385,solution)+'px) scale('+mix(.5,.7,solution)+')';
 const routeFaces=$$('.route-face'),handoff=smooth(f/20);routeFaces[0].style.background='rgb('+Math.round(mix(238,249,handoff))+','+Math.round(mix(113,188,handoff))+','+Math.round(mix(171,218,handoff))+')';routeFaces[1].style.background='rgb('+Math.round(mix(215,189,handoff))+','+Math.round(mix(190,118,handoff))+','+Math.round(mix(241,231,handoff))+')';
 routeFaces.forEach(el=>el.style.boxShadow="12px 14px 0 #382535");
 if(solution>0){routeFaces[0].style.background='#f99ac7';routeFaces[1].style.background='#c89ae9';const glow=Math.sin(clamp((f-b.keep)/18)*Math.PI)*16;routeFaces.forEach(el=>el.style.boxShadow='12px 14px 0 #382535,0 0 '+glow+'px #fff6bd')}
 const ide=1-ease((f-b.play)/10),tools=fade(f,b.remotion,b.play+7,8),play=fade(f,b.play,b.once+8,8),once=fade(f,b.once,b.variant+8,8),variant=fade(f,b.variant,b.copy+8,8),duplicate=fade(f,b.copy,b.time+8,8),retime=fade(f,b.time,b.water,8);
 set($('.code-ide'),ide*(1-tools*.48));$('.code-ide').style.transform='translateY('+((1-pop(f/14))*65)+'px)';paintCode($('.live-code'),170+f*15,Math.max(0,Math.floor((f-65)/15)));
 set($('.tool-icons'),tools);for(const [sel,at] of [['.remotion-tool',b.remotion],['.hyperframes-tool',b.hyperframes],['.html-tool',b.html]]){const el=$(sel),q=pop((f-at)/13);set(el,ease((f-at)/8));el.style.transform='translateY('+((1-q)*80)+'px) scale('+q+')'}
 set($('.motion-browser'),play);$('.motion-browser').style.transform='translateY('+((1-pop((f-b.play)/13))*75)+'px)';const pt=Math.max(0,f-b.play)/data.fps;
 $$('.toy').forEach((el,i)=>{const phase=pt*3.5+i*2.1,x=i===0?365+Math.sin(phase)*125:385+Math.cos(phase)*285,y=i===0?180+Math.cos(phase)*70:185+Math.sin(phase)*155;el.style.transform='translate('+x+'px,'+y+'px) rotate('+Math.sin(phase)*18+'deg) scale('+(1+.08*Math.sin(phase*1.5))+')'});
 $$('.pixel-spark').forEach((el,i)=>{const p=(pt*.55+i*.113)%1;el.style.left=(80+i*104)+'px';el.style.top=(70+p*470)+'px';el.style.transform='rotate('+Math.round(pt*6+i)*90+'deg) scale('+(Math.sin(p*Math.PI)*.8)+')';el.style.background=i%2?'#bf9fdd':'#f08abc'});
 set($('.once-stage'),once);const cycle=Math.max(1,(b.variant-b.once)/3),elapsed=Math.max(0,f-b.once),change=Math.min(2,Math.floor(elapsed/cycle));$$('.switch-shot').forEach((el,i)=>set(el,i===change?1:0));paintCode($('.reset-code'),200+Math.pow((elapsed%cycle)/cycle,.45)*2000,change*310);$('.rewrite-code').style.transform='translateY('+Math.sin((elapsed%cycle)/cycle*Math.PI)*-5+'px)';
 set($('.variant-stage'),variant);const vq=pop((f-b.variant)/14);$('.proposed-card').style.transform='translateX('+((1-vq)*100)+'px)';$('.proposed-card').style.borderColor=f%25<15?'#a957a7':'#d8acd5';
 set($('.duplicate-stage'),duplicate);paintCode($('.source-lines'),9999,2040+Math.max(0,Math.floor((f-b.copy)/5)));const dc=Math.max(0,f-b.copy)*22;paintCode($('.destination-lines'),dc%1750,Math.floor(dc/1750)*25);$('.code-transfer').style.transform='none';
 const burning=ease((f-b.tokens)/10);set($('.token-meter'),burning);$('.token-meter b').textContent=Math.round(12500+clamp((f-b.tokens)/Math.max(1,b.time-b.tokens))*337500).toLocaleString('en-US');$('.pixel-fire').style.transform='scale('+(1+Math.round(Math.sin(f*.9)*2)*.055)+') rotate('+Math.round(Math.sin(f*.4))*4+'deg)';
 set($('.retiming-stage'),retime);$$('.timing-row').forEach((row,i)=>{const rq=ease((f-b.time-i*4)/9);row.style.transform='translateX('+((1-rq)*80)+'px)';const body=row.querySelector('.row-script');set(body,ease((f-b.different-i*3)/9));const eq=ease((f-b.match-i*4)/9),slot=Math.max(1,(b.water-b.retime-5)/3),fix=clamp((f-b.retime-i*slot)/(slot*.8)),x=mix(origins[i],targets[i],smooth(fix));const chip=row.querySelector('.effect-chip');set(chip,eq);chip.style.left=x+'px';chip.style.transform='scale('+(.7+.3*pop((f-b.match-i*4)/12))+')';const tint=smooth(fix);chip.style.background='rgb('+Math.round(mix(207,197,tint))+','+Math.round(mix(184,223,tint))+','+Math.round(mix(237,191,tint))+')';row.querySelector('.effect-time').textContent=fix>=1?stamp[i]:fix>0?mix(parseFloat(stamp[i])*.35,parseFloat(stamp[i]),smooth(fix)).toFixed(2)+'s':'--.--s';const link=row.querySelector('.row-connector');set(link,eq);link.style.left=(x+56)+'px';});
 const pointer=$('.code-pointer');let px=820,py=465,pa=0,click=0;
 if(f<b.play){pa=1;const q=smooth((f-20)/16);px=mix(800,330,q);py=mix(1070,620,q);click=f>34&&f<45?1-(f-34)/11:0;}
 else if(f>=b.copy&&f<b.tokens){pa=1;const q=smooth((f-b.copy)/20);px=mix(350,790,q);py=mix(940,1070,q);click=f>b.copy+18&&f<b.copy+29?1-(f-b.copy-18)/11:0;}
 else if(f>=b.retime&&f<b.water){pa=1;const slot=Math.max(1,(b.water-b.retime-5)/3),i=Math.min(2,Math.floor((f-b.retime)/slot)),q=smooth(clamp((f-b.retime-i*slot)/(slot*.8)));px=42+mix(origins[i],targets[i],q)+65;py=465+i*254+166;click=0;}
 set(pointer,pa);pointer.style.transform='translate('+px+'px,'+py+'px)';set($('.code-click'),click);$('.code-click').style.transform='scale('+(1+(1-click)*1.4)+')';
 set($('.water-label'),water);$('.water-label').style.transform='translateY('+((1-pop((f-b.water)/12))*55)+'px)';$('.water-label i').style.opacity=String(.55+.45*Math.sin(f*.13)**2);
 set($('.synthesis-mark'),solution);$('.synthesis-mark').style.transform='translateY('+((1-pop((f-b.solution)/19))*80)+'px)';$('.synthesis-ring').style.backgroundPosition=(40+35*Math.sin(f*.035))+'% 0';$('.join-lines path').style.strokeDashoffset=String(1000*(1-ease((f-b.solution-8)/20)));
 const k=clamp((f-b.keep)/Math.max(12,b.drop-b.keep-4));$$('.kept-parts>div').forEach((el,i)=>{const q=smooth(clamp((k-i*.08)/.82)),x=mix(i?775:140,460,q),y=mix(1170,760,q)-Math.sin(q*Math.PI)*110;set(el,ease((f-b.parts-i*3)/8)*(1-ease((q-.85)/.15)));el.style.transform='translate('+x+'px,'+y+'px) scale('+(1-q*.5)+')';});const drop=clamp((f-b.drop)/Math.max(24,data.duration-b.drop));set($('.discarded'),f>=b.drop?1-ease((drop-.65)/.35):0);$$('.discarded span').forEach((el,i)=>{const age=f-b.drop-i*6,q=smooth(clamp((age-13)/Math.max(20,data.duration-b.drop-25)));set(el,ease(age/8)*(1-ease((q-.7)/.3)));el.style.transform='translate('+((i-1)*q*230)+'px,'+(q*q*670)+'px) rotate('+((i-1)*q*65)+'deg) scale('+(1-q*.3)+')';});
};`;
