export const module = { name: "@explainer/opening-system", version: "1" };
export const defaults = {
  Veil: {
    z: 20,
    pattern: "mesh",
    cell: 12,
    amount: 0.26,
    shade: 0.48,
    tint: "#0c101b",
    "fade-frames": 6,
  },
  Title: {
    z: 40,
    title: "Hypit",
    subtitle: "一分钟了解",
    seconds: 60,
    color: "#e0f5ff",
    "timer-y": 0.175,
    "title-y": 0.53,
    "title-size": 0.19,
  },
  Timer: {
    z: 80,
    title: "Hypit",
    subtitle: "VIDEO FRAMEWORK",
    seconds: 60,
    x: 0,
    y: 0.13,
    width: 0.28,
    accent: "#386f7e",
    "flag-color": "#c92f4d",
    "flag-amplitude": 0.06,
    "flag-speed": 0.25,
    "entrance-frames": 7,
  },
  Flag: { z: 35, x: 0.17, y: 0.81, width: 0.66, height: 0.17, "flag-color": "#fa67aa", "flag-amplitude": 0.04, "flag-speed": 0.25 },
  Stage: {
    z: 10,
    x: 0,
    y: 0.263,
    width: 1,
    height: 0.463,
    fit: "contain",
    blur: 32,
    brightness: 0.32,
    zoom: 1.13,
    radius: 0,
    "push-rate": 0,
  },
};
